### ISSUE TITLE
An error occurred while installing 

### ISSUE THREAD

**Issue by cyanrider** [willdurand/pihole-oled#1]
Hi, i cannot install this. This is the error code:

pi@Pihole128:~/pihole-oled $ pipenv install
Creating a virtualenv for this project…
Pipfile: /home/pi/pihole-oled/Pipfile
Using /usr/bin/python3 (3.5.3) to create virtualenv…
⠸ Creating virtual environment...Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pi/.local/share/virtualenvs/pihole-oled-4S8d8nXn/bin/python3
Also creating executable in /home/pi/.local/share/virtualenvs/pihole-oled-4S8d8nXn/bin/python
Installing setuptools, pip, wheel...
done.
✔ Successfully created virtual environment!
Virtualenv location: /home/pi/.local/share/virtualenvs/pihole-oled-4S8d8nXn
Installing dependencies from Pipfile.lock (715056)…
An error occurred while installing adafruit-pureio==0.2.3 --hash=sha256:e65cd929f1d8e109513ed1e457c2742bf4f15349c1a9b7f5b1e04191624d7488! Will try again.
An error occurred while installing pillow==5.4.1 --hash=sha256:051de330a06c99d6f84bcf582960487835bcae3fc99365185dc2d4f65a390c0e --hash=sha256:0ae5289948c5e0a16574750021bd8be921c27d4e3527800dc9c2c1d2abc81bf7 --hash=sha256:0b1efce03619cdbf8bcc61cfae81fcda59249a469f31c6735ea59badd4a6f58a --hash=sha256:163136e09bd1d6c6c6026b0a662976e86c58b932b964f255ff384ecc8c3cefa3 --hash=sha256:18e912a6ccddf28defa196bd2021fe33600cbe5da1aa2f2e2c6df15f720b73d1 --hash=sha256:24ec3dea52339a610d34401d2d53d0fb3c7fd08e34b20c95d2ad3973193591f1 --hash=sha256:267f8e4c0a1d7e36e97c6a604f5b03ef58e2b81c1becb4fccecddcb37e063cc7 --hash=sha256:3273a28734175feebbe4d0a4cde04d4ed20f620b9b506d26f44379d3c72304e1 --hash=sha256:4c678e23006798fc8b6f4cef2eaad267d53ff4c1779bd1af8725cc11b72a63f3 --hash=sha256:4d4bc2e6bb6861103ea4655d6b6f67af8e5336e7216e20fff3e18ffa95d7a055 --hash=sha256:505738076350a337c1740a31646e1de09a164c62c07db3b996abdc0f9d2e50cf --hash=sha256:5233664eadfa342c639b9b9977190d64ad7aca4edc51a966394d7e08e7f38a9f --hash=sha256:5d95cb9f6cced2628f3e4de7e795e98b2659dfcc7176ab4a01a8b48c2c2f488f --hash=sha256:7eda4c737637af74bac4b23aa82ea6fbb19002552be85f0b89bc27e3a762d239 --hash=sha256:801ddaa69659b36abf4694fed5aa9f61d1ecf2daaa6c92541bbbbb775d97b9fe --hash=sha256:825aa6d222ce2c2b90d34a0ea31914e141a85edefc07e17342f1d2fdf121c07c --hash=sha256:9c215442ff8249d41ff58700e91ef61d74f47dfd431a50253e1a1ca9436b0697 --hash=sha256:a3d90022f2202bbb14da991f26ca7a30b7e4c62bf0f8bf9825603b22d7e87494 --hash=sha256:a631fd36a9823638fe700d9225f9698fb59d049c942d322d4c09544dc2115356 --hash=sha256:a6523a23a205be0fe664b6b8747a5c86d55da960d9586db039eec9f5c269c0e6 --hash=sha256:a756ecf9f4b9b3ed49a680a649af45a8767ad038de39e6c030919c2f443eb000 --hash=sha256:b117287a5bdc81f1bac891187275ec7e829e961b8032c9e5ff38b70fd036c78f --hash=sha256:ba04f57d1715ca5ff74bb7f8a818bf929a204b3b3c2c2826d1e1cc3b1c13398c --hash=sha256:cd878195166723f30865e05d87cbaf9421614501a4bd48792c5ed28f90fd36ca --hash=sha256:cee815cc62d136e96cf76771b9d3eb58e0777ec18ea50de5cfcede8a7c429aa8 --hash=sha256:d1722b7aa4b40cf93ac3c80d3edd48bf93b9208241d166a14ad8e7a20ee1d4f3 --hash=sha256:d7c1c06246b05529f9984435fc4fa5a545ea26606e7f450bdbe00c153f5aeaad --hash=sha256:e9c8066249c040efdda84793a2a669076f92a301ceabe69202446abb4c5c5ef9 --hash=sha256:f227d7e574d050ff3996049e086e1f18c7bd2d067ef24131e50a1d3fe5831fbc --hash=sha256:fc9a12aad714af36cf3ad0275a96a733526571e52710319855628f476dcb144e! Will try again.
An error occurred while installing rpi.gpio==0.6.5 ; sys_platform == 'linux' --hash=sha256:a4210ad63bfe844e43995286de0d3950dfacfa0f3799bb9392770ac54a7d2e47! Will try again.
An error occurred while installing adafruit-ssd1306==1.6.2 --hash=sha256:4768518204037db82eb6b90838938f8519ecd29fe3d6cc3efa0d1100ed527727! Will try again.
An error occurred while installing adafruit-gpio==1.0.3 --hash=sha256:d6465b92c866c51ca8f3bc1e8f2ec36f5ccdb46d0fd54101c1109756d4a2dcd0! Will try again.
An error occurred while installing psutil==5.5.1 --hash=sha256:5ce6b5eb0267233459f4d3980c205828482f450999b8f5b684d9629fea98782a --hash=sha256:72cebfaa422b7978a1d3632b65ff734a34c6b34f4578b68a5c204d633756b810 --hash=sha256:77c231b4dff8c1c329a4cd1c22b96c8976c597017ff5b09993cd148d6a94500c --hash=sha256:8846ab0be0cdccd6cc92ecd1246a16e2f2e49f53bd73e522c3a75ac291e1b51d --hash=sha256:a013b4250ccbddc9d22feca0f986a1afc71717ad026c0f2109bbffd007351191 --hash=sha256:ad43b83119eeea6d5751023298cd331637e542cbd332196464799e25a5519f8f --hash=sha256:c177777c787d247d02dae6c855330f9ed3e1abf8ca1744c26dd5ff968949999a --hash=sha256:ec1ef313530a9457e48d25e3fdb1723dfa636008bf1b970027462d46f2555d59 --hash=sha256:ef3e5e02b3c5d1df366abe7b4820400d5c427579668ad4465ff189d28ded5ebd! Will try again.
An error occurred while installing humanize==0.5.1 --hash=sha256:a43f57115831ac7c70de098e6ac46ac13be00d69abbf60bdcac251344785bb19! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 12/12 — 00:05:25
Installing initially failed dependencies…
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 7/7 — 00:03:16
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/cli/command.py", line 254, in install
[pipenv.exceptions.InstallError]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 862, in do_install_dependencies
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, False, failed_deps_queue, retry=False)
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple', 'Collecting adafruit-pureio==0.2.3 (from -r /tmp/pipenv-ffy4gmd9-requirements/pipenv-b6qvgxoy-requirement.txt (line 1))', '  Using cached https://www.piwheels.org/simple/adafruit-pureio/Adafruit_PureIO-0.2.3-py3-none-any.whl']
[pipenv.exceptions.InstallError]: ['ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.', '    adafruit-pureio==0.2.3 from https://www.piwheels.org/simple/adafruit-pureio/Adafruit_PureIO-0.2.3-py3-none-any.whl#sha256=89ff5a0da2cfa6643978929c44743c432680141823e783d6001eb3aab368cc20 (from -r /tmp/pipenv-ffy4gmd9-requirements/pipenv-b6qvgxoy-requirement.txt (line 1)):', '        Expected sha256 e65cd929f1d8e109513ed1e457c2742bf4f15349c1a9b7f5b1e04191624d7488', '             Got        89ff5a0da2cfa6643978929c44743c432680141823e783d6001eb3aab368cc20']
ERROR: ERROR: Package installation failed...

Do you have an idea?

Best regards

**Comment by MajesticUnicorns99** [comment]
Looks like running `pipenv install update` is doing the trick for me, updating the .lock file and then running `pipenv install`

**Comment by MajesticUnicorns99** [comment]
Scratch that `pipenv install --skip-lock` did the trick

**Comment by willdurand** [comment]
Oh, interesting. I will update the lock file then. Thanks!

**Comment by cyanrider** [comment]
> Scratch that `pipenv install --skip-lock` did the trick

that worked. thx :)
