### ISSUE TITLE
install pipenv fails

### ISSUE THREAD

**Issue by Maschine2501** [willdurand/pihole-oled#4]
Hi!
I'm Using a Pi Zero W with Raspbian Buster Lite.
I've installed Python 3.5.6 and then followed the installation steps.

But everytime, in the step "pipenv install" it fails at step 12/13.

I have absolutely no clou, why it fails...
Maybe you can help me?

Log:

pi@raspberrypi:~/pihole-oled $ pipenv install
Installing dependencies from Pipfile.lock (715056)…
An error occurred while installing pillow==7.0.0 --hash=sha256:0a628977ac2e01ca9                                     6aaae247ec2bd38e729631ddf2221b4b715446fd45505be --hash=sha256:4d9ed9a64095e03143                                     5af120d3c910148067087541131e82b3e8db302f4c8946 --hash=sha256:54ebae163e8412aff0b                                     9df1e88adab65788f5f5b58e625dc5c7f51eaf14a6837 --hash=sha256:5bfef0b1cdde9f33881c                                     913af14e43db69815c7e8df429ceda4c70a5e529210f --hash=sha256:5f3546ceb08089cedb9e8                                     ff7e3f6a7042bb5b37c2a95d392fb027c3e53a2da00 --hash=sha256:5f7ae9126d16194f114435                                     ebb79cc536b5682002a4fa57fa7bb2cbcde65f2f4d --hash=sha256:62a889aeb0a79e50ecf5af2                                     72e9e3c164148f4bd9636cc6bcfa182a52c8b0533 --hash=sha256:7406f5a9b2fd966e79e6abda                                     f700585a4522e98d6559ce37fc52e5c955fade0a --hash=sha256:8453f914f4e5a3d828281a662                                     8cf517832abfa13ff50679a4848926dac7c0358 --hash=sha256:87269cc6ce1e3dee11f23fa515                                     e4249ae678dbbe2704598a51cee76c52e19cda --hash=sha256:875358310ed7abd5320f21dd973                                     51d62de4929b0426cdb1eaa904b64ac36b435 --hash=sha256:8ac6ce7ff3892e5deaab7abaec76                                     3538ffd011f74dc1801d93d3c5fc541feee2 --hash=sha256:91b710e3353aea6fc758cdb7136d9                                     bbdcb26b53cefe43e2cba953ac3ee1d3313 --hash=sha256:9d2ba4ed13af381233e2d810ff3bab                                     84ef9f18430a9b336ab69eaf3cd24299ff --hash=sha256:a62ec5e13e227399be73303ff301f28                                     65bf68657d15ea50b038d25fc41097317 --hash=sha256:ab76e5580b0ed647a8d8d2d2daee170e                                     8e9f8aad225ede314f684e297e3643c2 --hash=sha256:bf4003aa538af3f4205c5fac56eacaa67                                     a6dd81e454ffd9e9f055fff9f1bc614 --hash=sha256:bf598d2e37cf8edb1a2f26ed3fb255191f                                     5232badea4003c16301cb94ac5bdd0 --hash=sha256:c18f70dc27cc5d236f10e7834236aff60aa                                     dc71346a5bc1f4f83a4b3abee6386 --hash=sha256:c5ed816632204a2fc9486d784d8e0d0ae754                                     347aba99c811458d69fcdfd2a2f9 --hash=sha256:dc058b7833184970d1248135b8b0ab702e6da                                     a833be14035179f2acb78ff5636 --hash=sha256:ff3797f2f16bf9d17d53257612da84dd0758db                                     33935777149b3334c01ff68865! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 13/13 — 00:06:26
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 1874, in
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 1253, in
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 859, in d
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 763, in b
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/core.py", line 681, in _
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple', 'Cw', '  Building wheel for pillow (setup.py): started', "  Building wheel for pillow (setup.py): finished with status  Running setup.py install for pillow: started', "    Running setup.py install for pillow: finished with status 'error
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '   command: /home/pi/.local/shainstall-3746o7ll/pillow/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-3746o7ll/pillow/setup.py\'"\'"\';f=getattlose();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d /tmp/pip-wheel-hmuos8wl', '       cwd: /tng build_py', '  creating build', '  creating build/lib.linux-armv6l-3.5', '  creating build/lib.linux-armv6l-3.5/PILib.linux-armv6l-3.5/PIL', '  copying src/PIL/JpegPresets.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/IpPIL', '  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/ImagePalette.py -> ImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv6 build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying mv6l-3.5/PIL', '  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/_binapying src/PIL/PdfParser.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/ImageFile.py -> build/lib.linux-armuild/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying sarmv6l-3.5/PIL', '  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/Sgi copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/PpmImagePlugin.py -> build/ContainerIO.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv6l-3.linux-armv6l-3.5/PIL', '  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/XVL', '  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/ImageChops.py -> buil/ImageMode.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/TarIO.py -> build/lib.linux-armv6l-3.5/PIL', '  v6l-3.5/PIL', '  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/__mainpying src/PIL/ImageOps.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/SunImagePlugin.py -> build/lib.linux> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/ImageQt.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/P3.5/PIL', '  copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/FtexImagePluging src/PIL/ImageSequence.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/IcnsImagePlugin.py -> build/lib.lingin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/ImageDraw.py -> build/lib.linux-armv6l-3.5/PIL', '  copux-armv6l-3.5/PIL', '  copying src/PIL/ImageShow.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/MpegImagePying src/PIL/ImageTk.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/FliImagePlugin.py -> build/lib.linux-a> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/features.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/5/PIL', '  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/ImageColor.py -> /PIL/__init__.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv6l-3ild/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying sv6l-3.5/PIL', '  copying src/PIL/_util.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/PalmImagePlugin.py -src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  copying src/PIL/TiffTags.py -> build/lib.linux-arld/lib.linux-armv6l-3.5/PIL', '  running egg_info', '  writing dependency_links to src/Pillow.egg-info/dependency_linreading manifest file 'src/Pillow.egg-info/SOURCES.txt'", "  reading manifest template 'MANIFEST.in'", "  warning: no  warning: no previously-included files found matching '.appveyor.yml'", "  warning: no previously-included files fouiously-included files found matching '.editorconfig'", "  warning: no previously-included files found matching '.read-included files matching '.git*' found anywhere in distribution", "  warning: no previously-included files matching 'ibution", "  no previously-included directories found matching '.azure-pipelines'", "  no previously-included directocompiling is disabled, skipping.', '  ', '  running build_ext', '  ', '  ', '  The headers or library files could notructions at:', '     https://pillow.readthedocs.io/en/latest/installation.html', '  ', '  Traceback (most recent calld() or PLATFORM_MINGW),', '    File "/home/pi/.local/share/virtualenvs/pihole-oled-4S8d8nXn/lib/python3.5/site-packag/python3.5/distutils/core.py", line 148, in setup', '      dist.run_commands()', '    File "/usr/local/lib/python3.5/tils/dist.py", line 974, in run_command', '      cmd_obj.run()', '    File "/home/pi/.local/share/virtualenvs/pihole-    File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command', '      self.distribution.run_command   File "/usr/local/lib/python3.5/distutils/command/build.py", line 135, in run', '      self.run_command(cmd_name)',command)', '    File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command', '      cmd_obj.run()',  '    File "/tmp/pip-install-3746o7ll/pillow/setup.py", line 687, in build_extensions', '      raise RequiredDependenr exception occurred:', '  ', '  Traceback (most recent call last):', '    File "<string>", line 1, in <module>', '  )', '  __main__.RequiredDependencyException:', '  ', '  The headers or library files could not be found for jpeg,', 'tps://pillow.readthedocs.io/en/latest/installation.html', '  ', '  ', '  ----------------------------------------', 'i/.local/share/virtualenvs/pihole-oled-4S8d8nXn/bin/python -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\stall-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.local/share/virtualenvs/piut (176 lines):', '    running install', '    running build', '    running build_py', '    creating build', '    creay -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/ImageStat.py -> build/lib.linux-armv6l-3.5/PIL', '    copyx-armv6l-3.5/PIL', '    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/ImIL', '    copying src/PIL/PSDraw.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/BlpImagePlugin.py -> buing src/PIL/GimpGradientFile.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/PyAccess.py -> build/lib.linugePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv6l-3.5/ build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copl-3.5/PIL', '    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/ExifTags.pyying src/PIL/PngImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/SpiderImagePlugin.py -> build src/PIL/SgiImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/ImageCms.py -> build/lib.linux-arPlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv6l-3.5/Puild/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/ImageGrab.py -> build/lib.linux-armv6l-3.5/PIL', '    copying sr.5/PIL', '    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/ImageMat copying src/PIL/ImageChops.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/IcoImagePlugin.py -> build/liO.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv6l-3.5/PIL', '   b.linux-armv6l-3.5/PIL', '    copying src/PIL/__main__.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/Ps '    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/EpsImagePlugin.py ->/ImageQt.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv6l-3.5/-> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    inux-armv6l-3.5/PIL', '    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PI5/PIL', '    copying src/PIL/ImageDraw.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/DcxImagePlugin.py ing src/PIL/ImageShow.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/MpegImagePlugin.py -> build/lib.linpy -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '  ux-armv6l-3.5/PIL', '    copying src/PIL/features.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/XpmImag    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/ImageColor.py -> buildPIL/__init__.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv6l--> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    b.linux-armv6l-3.5/PIL', '    copying src/PIL/_util.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/PalmIPIL', '    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv6l-3.5/PIL', '    copying src/PIL/TiffTags.py rc/PIL/FontFile.py -> build/lib.linux-armv6l-3.5/PIL', '    running egg_info', '    writing top-level names to src/Pirc/Pillow.egg-info/PKG-INFO', "    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'", "    reading manifest tewarning: no files found matching '*.sh'", "    warning: no previously-included files found matching '.appveyor.yml'",und matching '.codecov.yml'", "    warning: no previously-included files found matching '.editorconfig'", "    warninching 'azure-pipelines.yml'", "    warning: no previously-included files matching '.git*' found anywhere in distributiously-included files matching '*.so' found anywhere in distribution", "    no previously-included directories found ile 'src/Pillow.egg-info/SOURCES.txt'", '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    endency when compiling Pillow from source.', '    ', '    Please see the install instructions at:', '       https://pip-install-3746o7ll/pillow/setup.py", line 892, in <module>', '        zip_safe=not (debug_build() or PLATFORM_MINGW)py", line 144, in setup', '        return distutils.core.setup(**attrs)', '      File "/usr/local/lib/python3.5/distupy", line 955, in run_commands', '        self.run_command(cmd)', '      File "/usr/local/lib/python3.5/distutils/dis8d8nXn/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run', '        return orig.install.runnd('build')", '      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command', '        self.distr     cmd_obj.run()', '      File "/usr/local/lib/python3.5/distutils/command/build.py", line 135, in run', '        s self.distribution.run_command(command)', '      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_un', '        self.build_extensions()', '      File "/tmp/pip-install-3746o7ll/pillow/setup.py", line 687, in build_e   During handling of the above exception, another exception occurred:', '    ', '    Traceback (most recent call lasn <module>', '        raise RequiredDependencyException(msg)', '    __main__.RequiredDependencyException:', '    ', 'urce.', '    ', '    Please see the install instructions at:', '       https://pillow.readthedocs.io/en/latest/instalus 1: /home/pi/.local/share/virtualenvs/pihole-oled-4S8d8nXn/bin/python -u -c \'import sys, setuptools, tokenize; syssetup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"d-zhakks80/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.local/share/v
ERROR: ERROR: Package installation failed...

**Comment by Maschine2501** [comment]
Solved my problem otherwise: https://github.com/Maschine2501/pihole-oled

**Comment by willdurand** [comment]
the error looks like pipenv issues but that's not surprising because of... well, pipenv. I thought having a lockfile would make things more reproducible but that's quite the contrary it seems. That's annoying but removing the lockfile should fix the issue.

I saw your fork so I guess you don't mind, but feel free to propose a patch with the other lib you used if the problem comes from the adafruit one.

I'll see if I can switch back to pip + hashin

**Comment by Maschine2501** [comment]
Hi,
I don't know how pipenv and the lockfile works...
Maybe i'll learn it some time (and try it with my repos...), but actually i can't provide you a patch.
Maybe you'll have a look at my fork and the installation instructions... -> even python 3.5(.x) is not needed with a Raspbian Buster image.
By the way...:
I'm trying to pump up the code for dualscreen and fritzbox api support ^^
